# Generated by Django 3.0.8 on 2020-08-02 23:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(max_length=25)),
                ('budget', models.FloatField(max_length=8)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Complete', 'Complete')], max_length=8)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)])),
                ('lastname', models.CharField(max_length=25)),
                ('firstname', models.CharField(max_length=25)),
                ('street_address', models.CharField(max_length=50)),
                ('suburb', models.CharField(max_length=15)),
                ('hourly_rate', models.FloatField(validators=[django.core.validators.MaxValueValidator(75.0), django.core.validators.MinValueValidator(10.0)])),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='morgan.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(1)])),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='morgan.Employee')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='morgan.Project')),
            ],
        ),
    ]
