# Generated by Django 3.0.8 on 2020-08-02 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morgan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'managed': False},
        ),
    ]
