# Generated by Django 3.0.8 on 2020-08-03 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morgan', '0002_auto_20200802_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterModelTable(
            name='assignment',
            table='morgan_assignment',
        ),
    ]
